---
- name: Update all nodes install vim, net-tools, disable swap & firewall, install docker helper packages
  hosts: vmclusterkicnodes
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: Disable swap and firewall
      shell: |
        sudo swapoff -a
        sudo sed -i '/swap/ s/^/#/' /etc/fstab
        sudo ufw disable
      args:
        executable: /bin/bash
    - name: Install vim, net-tools and docker helper package
      become: yes
      apt:
        pkg:
          - vim
          - net-tools
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update-cache: yes
    - name: Implement update docker sources list
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash
    - name: Install docker
      become: yes
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update-cache: yes
    - name: Run docker as regular user
      shell: |
        sudo groupadd -f docker
        sudo usermod --append --groups docker $USER
      args:
        executable: /bin/bash
    - name: Configure docker to use systemd as the cgroup filesystem driver
      shell: |
        cat <<EOF | sudo tee /etc/docker/daemon.json
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
        EOF
      args:
        executable: /bin/bash
    - name: Reload docker
      shell: |
        sudo systemctl enable docker
        sleep 2
        sudo systemctl daemon-reload
        sleep 2
        sudo systemctl restart docker
      args:
        executable: /bin/bash
    - name: Implement tab completion
      shell: |
        sudo curl https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker -o /etc/bash_completion.d/docker.sh
        echo 'alias d=/usr/bin/docker' >>~/.bashrc
        echo 'complete -F _docker d' >>~/.bashrc
      args:
        executable: /bin/bash

- name: Update master node
  hosts: vmclusterkicnodes[0]
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: change hostname
      shell: |
        sudo hostnamectl set-hostname master
        sudo sed -i 's/testenv-.*/master/g' /etc/hosts
      args:
        executable: /bin/bash

- name: Update worker1 node
  hosts: vmclusterkicnodes[1]
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: change hostname
      shell: |
        sudo hostnamectl set-hostname worker1
        sudo sed -i 's/testenv-.*/worker1/g' /etc/hosts
      args:
        executable: /bin/bash

- name: Update worker2 node
  hosts: vmclusterkicnodes[2]  
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: change hostname
      shell: |
        sudo hostnamectl set-hostname worker2
        sudo sed -i 's/testenv-.*/worker2/g' /etc/hosts
      args:
        executable: /bin/bash

- name: Install kubernetes
  hosts: vmclusterkicnodes
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: Load br_filter and set net bridge iptables to 1 in sysclt
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        br_netfilter
        EOF
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
    - name: Install supporting packages
      become: yes
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
        update-cache: yes
    - name: Add kubernetes repo
      shell: | 
        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: Install kubeadm, kubelet and kubectl
      shell: |
        sudo apt-get update
        sudo apt-get install -y kubelet kubeadm kubectl
        sudo apt-mark hold kubelet kubeadm kubectl

- name: Initialize kubeadm on master node
  hosts: vmclusterkicnodes[0]
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: Run kubeadmin init command
      shell: sudo kubeadm init --control-plane-endpoint {{ host1 }} --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
    - name: copy admin.conf to user's kube config
      shell: |
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: install pod network
      shell: | 
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    - name: add tab completion
      shell: |
        echo 'source /usr/share/bash-completion/bash_completion' >>~/.bashrc
        echo 'source <(kubectl completion bash)' >>~/.bashrc
        echo 'alias k=kubectl' >>~/.bashrc
        echo 'complete -F __start_kubectl k' >>~/.bashrc
    - name: Get the token for joining the worker nodes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command
    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"
    - name: Copy join command to local file
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- name: Initialize workers
  hosts: vmclusterkicnodes[1:]
  become: yes
  gather_facts: yes
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: Copy join command from Ansiblehost to the worker nodes
      become: yes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777
    - name: Join the Worker nodes to the cluster
      become: yes
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
    - name: add tab completion
      shell: |
        echo 'source /usr/share/bash-completion/bash_completion' >>~/.bashrc
        echo 'source <(kubectl completion bash)' >>~/.bashrc
        echo 'alias k=kubectl' >>~/.bashrc
        echo 'complete -F __start_kubectl k' >>~/.bashrc

- name: Add worker labels to worker nodes
  hosts: vmclusterkicnodes[0]
  vars_files:
    - /tmp/vmclusterkicvars
  tasks:
    - name: add worker label to worker nodes
      shell: |
        kubectl label node worker1 node-role.kubernetes.io/worker=worker
        kubectl label node worker2 node-role.kubernetes.io/worker=worker

