---
backend:
  url: https://testenv-backend.westus2.cloudapp.azure.com/api/v1
  token: 6b93996fd09c1b4b0258a7d32320087dc5a48779

vault:
  token: null

projects:
  - name: indigo
    repo: https://gitlab+deploy-token-240971:PYj3t7nszQDATVcgeDG5@gitlab.com/f5/nginx/tools/testenv/project-indigo.git

defaults:
  public_key: ~/.ssh/id_rsa.pub

  cloud: aws
  project: indigo
  public_key: ~/.ssh/id_rsa.pub # optional

aws:
  profile: dev-sandbox-Users-641222230151
  region: us-west-2  # optional

vsphere:
  username: _prdblusilversurfer@olympus
  password: XFF1hHX^tdJ5iS
