---
- name: Install NIM
  hosts: testenv
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: install apache2-utils (for htpasswd use)
      apt:
        name: "apache2-utils"
        state: present
      become: true
    - name: add repo key for ClickHouse
      apt_key:
        keyserver: "hkp://keyserver.ubuntu.com:80"
        id: "8919F6BD2B48D754"
      become: true
    - name: add repo for ClickHouse
      apt_repository:
        repo: "deb https://packages.clickhouse.com/deb stable main"
        filename: "/etc/apt/sources.list.d/clickhouse.list"
        state: present
      become: true
    - name: install Clickhouse server
      apt:
        name: "clickhouse-server"
        state: present
        force: yes
      become: true
    - name: install Clickhouse client
      apt:
        name: "clickhouse-client"
        state: present
        force: yes
      become: true
    - name: ensure that ClickHouse is running
      systemd:
        state: started
        name: clickhouse-server
      become: true
    - name: Add nginx_signing.key to apt
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present
    - name: Update apt sources with NGINX Instance Manager (nms)
      shell: |
        printf "deb https://pkgs.nginx.com/nms/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nms.list
        sudo wget -q -O /etc/apt/apt.conf.d/90pkgs-nginx https://cs.nginx.com/static/files/90pkgs-nginx
    - name: Install Nginx Instance Manager
      become: yes
      apt:
        pkg: nms-instance-manager
        state: present
        update-cache: yes
    - name: Enable nms resources and set admin user
      shell: |
        sudo systemctl enable nms-core
        sudo systemctl enable nms-dpm
        sudo systemctl enable nms-ingestion
        sudo systemctl enable nms
        htpasswd -b /etc/nms/nginx/.htpasswd admin admin
    - name: Reload NGINX
      shell: sudo nginx -s reload
    - name: Start NGINX Instance Manager
      shell: sudo systemctl start nms
