# cafe and bar services
server {
    listen 8081;
    return 200 '{"service": "coffee:8081", "value": "I love coffee!"}';
}
server {
    listen 8082;
    return 200 '{"service": "coffee:8082", "value": "I love coffee!"}';
}
server {
    listen 8083;
    return 200 '{"service": "tea:8083", "value": "I love tea!"}';
}
server {
    listen 8084;
    return 200 '{"service": "tea:8084", "value": "I love tea!"}';
}
server {
    listen 8085;
    return 200 '{"service": "beer:8085", "value": "I love beer!"}';
}
server {
    listen 8086;
    return 200 '{"service": "beer:8086", "value": "I love beer!"}';
}
server {
    listen 8087;
    return 200 '{"service": "wine:8087", "value": "I love wine!"}';
}
server {
    listen 8088;
    return 200 '{"service": "wine:8088", "value": "I love wine!"}';
}
