# Datplane for cafe and bar services
log_format my_log_format '$remote_addr - "$remote_user" [$time_local] "$request" $status $proxy_protocol_addr ra=$remote_addr  proxy_add_x_forwarded_for=$proxy_add_x_forwarded_for $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$host" sn="$server_name" rt="$request_time" ua="$upstream_addr" us="$upstream_status" ut="$upstream_response_time" ul="$upstream_response_length" cs="$upstream_cache_status" upgrd=$http_upgrade';
access_log /var/log/nginx/access.log my_log_format;
error_log /var/log/nginx/error.log;
server_tokens off;
server_names_hash_bucket_size 128;
upstream coffee {
	zone coffee_http 1280k;
	server localhost:8081;
	server localhost:8082;
	keepalive 64;
	keepalive_requests 100;
	keepalive_timeout 60s;
}
upstream tea {
	zone tea_http 1280k;
	server localhost:8083;
	server localhost:8084;
	keepalive 64;
	keepalive_requests 100;
	keepalive_timeout 60s;
}
upstream beer {
	zone beer_http 1280k;
	server localhost:8085;
	server localhost:8086;
	keepalive 64;
	keepalive_requests 100;
	keepalive_timeout 60s;
}
upstream wine {
	zone wine_http 1280k;
	server localhost:8087;
	server localhost:8088;
	keepalive 64;
	keepalive_requests 100;
	keepalive_timeout 60s;
}
# dataplane for default localhost and cafe services
server {
	listen 80 default_server;
	server_name localhost cafe.example.com;
    	location / {
        	root   /usr/share/nginx/html;
        	index  index.html index.htm;
    	}
    	error_page  404              /404.html;
    	# redirect server error pages to the static page /50x.html
    	#
    	error_page   500 502 503 504  /50x.html;
    	location = /50x.html {
        	root   /usr/share/nginx/html;
    	}
	location /coffee {
		proxy_set_header Connection '';
		proxy_set_header X-Real-IP-remote_addr $remote_addr;
		proxy_set_header Upgrade $http_upgrade;
		proxy_pass_request_headers on;
		proxy_set_header X-Forwarded-proxy_add_x_forwarded_for $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-host $host;
		proxy_set_header X-Forwarded-server_addr $server_addr;
		proxy_set_header X-Forwarded-server_port $server_port;
		proxy_set_header X-Forwarded-remote_addr $remote_addr;
		proxy_set_header X-Forwarded-remote_port $remote_port;
		proxy_set_header X-Forwarded-proxy_protocol_addr $proxy_protocol_addr;
		proxy_set_header X-Forwarded-proxy_protocol_port $proxy_protocol_port;
		proxy_set_header X-Forwarded-Proto-scheme $scheme;
		proxy_set_header Host "$host";
		proxy_http_version 1.1;
		proxy_pass http://coffee;
	}
	location /tea {
		proxy_http_version 1.1;
		proxy_pass http://tea;
	}
}
# dataplane for bar services
server {
	listen 80;
	server_name bar.example.com;
	location /beer {
		proxy_http_version 1.1;
		proxy_pass http://beer;
	}
	location /wine {
		proxy_http_version 1.1;
		proxy_pass http://wine;
	}
}
