---
- name: Install NGINX+ on Centos
  hosts: testenv
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: Firewall
      shell: |
        sudo systemctl disable firewalld
        sudo systemctl stop firewalld
      args:
        executable: /bin/bash
      ignore_errors: True
    - name: Install vim, net-tools, curl, wget, gnupg, ca-certificates, epel-release, bash-completion and httpd-tools
      become: yes
      yum:
        name:
          - vim
          - net-tools
          - curl
          - wget
          - gnupg
          - ca-certificates
          - epel-release
          - httpd-tools
          - bash-completion
        state: present
        expire-cache: yes
    - name: Create nginx directory (for nginx.repo cert)
      command: sudo mkdir -p /etc/ssl/nginx
    - name: Copy nginx.repo.crt to /etc/ssl/nginx/
      become: yes
      copy:
        src: ~/Documents/NGINX/NGINX-Trials/NGINXPlus/ValidCert/nginx-repo.crt
        dest: /etc/ssl/nginx/nginx-repo.crt
    - name: Copy nginx.repo.key to /etc/ssl/nginx/
      become: yes
      copy:
        src: ~/Documents/NGINX/NGINX-Trials/NGINXPlus/ValidCert/nginx-repo.key
        dest: /etc/ssl/nginx/nginx-repo.key
    - name: Download nginx and app protect keys
      shell: | 
        sudo wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/nginx-plus-7.4.repo
        sudo wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/app-protect-7.repo
        sudo wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/modsecurity-7.repo
    - name: Install nginx-plus, app-protect and modsecurity module
      become: yes
      yum: 
        name:
          - nginx-plus-25-2.el7.ngx.x86_64
          - nginx-plus-module-appprotect-25+3.760.0-1.el7.ngx.x86_64
          - app-protect-attack-signatures
          - nginx-plus-module-modsecurity-25+1.0.2-3.el7.ngx.x86_64
        state: present
        expire-cache: yes
    - name: Enable nginx.service
      command: sudo systemctl enable nginx.service
    - name: Enable nginx
      command: sudo nginx
