---
- name: Implement beverages services to nginx
  hosts: testenv
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: Get state of /etc/nginx/conf.d/default.conf
      stat: path=/etc/nginx/conf.d/default.conf
      register: ngx_default_conf
    - name: Rename /etc/nginx/conf.d/default.conf to remove it from nginx processing
      command: sudo mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
      when: ngx_default_conf.stat.exists
    - name: Copy beverages.conf to /etc/nginx/conf.d/
      become: yes
      copy:
        src: beverages.conf
        dest: /etc/nginx/conf.d/
    - name: Copy main_nginx.conf to /etc/nginx/conf.d/
      become: yes
      copy:
        src: main_nginx.conf
        dest: /etc/nginx/conf.d/
    - name: Reload nginx
      command: sudo nginx -s reload
