---
- name: Update nginx nodes
  hosts: ngxnodes
  vars_files:
    - ~/.testenv/my/ansible/playbooks/group_vars/ngxvars
  tasks: 
    - name: Update apt
      command: "sudo apt update"
    - name: Install vim
      command: "sudo apt install vim -y"
    - name: Create done file
      command: "touch /var/tmp/UpdatedAll"

