---
- name: Update all vm-cluster nodes
  hosts: vmclusternodes
  vars_files:
    - ~/.testenv/my/ansible/playbooks/group_vars/vmclusternicvars
  tasks:
    - name: Update apt and install vim and net-tools
      apt:
        pkg:
          - vim
          - net-tools
        update-cache: yes
    - name: Disable swap
      command: "sudo swapoff -a"
    - name: Remove swap file
      command: "sudo sed -i '/swap/ s/^/#/' /etc/fstab"
    - name: Disable firewall
      command: "sudo ufw disable"
    - name: Install docker helper packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    

