---
- name: Create Kubernetes Cluster with Containerd CRI
  hosts: testenv
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: Disable swap and firewall
      shell: |
        sudo swapoff -a
        sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
        sudo ufw disable
      args:
        executable: /bin/bash
    - name: Install vim, net-tools, ca-certs, curl, gnupg, lsb-release, apt-transport-https
      become: yes
      apt:
        pkg:
          - vim
          - net-tools
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - apt-transport-https
        update-cache: yes
    - name: Setup Docker repo
      shell: |
        sudo apt-get update
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash
    - name: Install Docker Engine
      become: yes
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update-cache: yes
    - name: Run docker as regular user
      shell: |
        sudo usermod -aG docker $USER
      args:
        executable: /bin/bash
    - name: Implement Docker tab completion
      shell: |
        sudo curl https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker -o /etc/bash_completion.d/docker.sh
        echo 'alias d=/usr/bin/docker' >>~/.bashrc
        echo 'complete -F _docker d' >>~/.bashrc
      args:
        executable: /bin/bash
    - name: Implement Kuberntes Runtime Prerequisites
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        sudo modprobe overlay
        sudo modprobe br_netfilter
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF
        sudo sysctl --system
    - name: Install Containerd
      shell: |
        wget https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
        sudo tar Czxvf /usr/local containerd-1.6.6-linux-amd64.tar.gz
        wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        sudo mv containerd.service /usr/lib/systemd/system/
        wget https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64
        sudo install -m 755 runc.amd64 /usr/local/sbin/runc
    - name: Configure Containerd
      shell: |
        sudo mkdir -p /etc/containerd
        sudo containerd config default | sudo tee /etc/containerd/config.toml
        sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
        sudo systemctl daemon-reload
        sudo systemctl enable --now containerd
        sudo systemctl restart containerd
        sudo systemctl status containerd
    - name: Install Kubernetes via Kubeadm
      shell: |
        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt update
        sudo apt-get install -y kubelet kubeadm kubectl
        sudo apt-mark hold kubelet kubeadm kubectl
- name: Change hostname on master node
  hosts: testenv[0]
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: set hostname to master
      shell: |
        sudo hostnamectl set-hostname master
        sudo sed -i 's/testenv-.*/master/g' /etc/hosts
      args:
        executable: /bin/bash
- name: Change hostname on worker node 1
  hosts: testenv[1]
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: set hostname to worker1
      shell: |
        sudo hostnamectl set-hostname worker1
        sudo sed -i 's/testenv-.*/worker1/g' /etc/hosts
      args:
        executable: /bin/bash
- name: Change hostname to worker2
  hosts: testenv[2]  
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: set hostname to worker2 
      shell: |
        sudo hostnamectl set-hostname worker2
        sudo sed -i 's/testenv-.*/worker2/g' /etc/hosts
      args:
        executable: /bin/bash
- name: Initialize kubeadm on master node
  hosts: testenv[0]
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: Run kubeadmin init command
      shell: sudo kubeadm init --control-plane-endpoint {{ host1 }} --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
    - name: Create kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
    - name: copy admin.conf to user's kube config
      shell: |
        sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Install pod network (calico)
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    - name: add tab completion
      shell: |
        echo 'source /usr/share/bash-completion/bash_completion' >>~/.bashrc
        echo 'source <(kubectl completion bash)' >>~/.bashrc
        echo 'alias k=kubectl' >>~/.bashrc
        echo 'complete -F __start_kubectl k' >>~/.bashrc
    - name: Get the token for joining the worker nodes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command
    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"
    - name: Copy join command to local file
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
    - name: Copy kube config file to /tmp
      shell: cp $HOME/.kube/config /tmp/masterkubeconfig
    - name: Copy remote kube config file to local /tmp
      fetch: 
        src: /tmp/masterkubeconfig
        dest: /tmp/
        flat: yes
- name: Initialize workers
  hosts: testenv[1:]
  gather_facts: yes
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: Copy join command from Ansiblehost to the worker nodes
      become: yes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777
    - name: Join the Worker nodes to the cluster
      become: yes
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
    - name: copy local kube config file to remote /tmp
      copy:
        src: /tmp/masterkubeconfig
        dest: /tmp/masterkubeconfig
        mode: 0777
    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
    - name: Copy master kube config to home directory
      shell: |
        sudo cp /tmp/masterkubeconfig $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: add tab completion
      shell: |
        echo 'source /usr/share/bash-completion/bash_completion' >>~/.bashrc
        echo 'source <(kubectl completion bash)' >>~/.bashrc
        echo 'alias k=kubectl' >>~/.bashrc
        echo 'complete -F __start_kubectl k' >>~/.bashrc
- name: Add worker labels to worker nodes
  hosts: testenv[0]
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: add worker label to worker nodes
      shell: |
        kubectl label node worker1 node-role.kubernetes.io/worker=worker
        kubectl label node worker2 node-role.kubernetes.io/worker=worker

