---
- name: Install NGINX+ on Ubuntu
  hosts: testenv
  vars_files:
    - /tmp/testenvansiblevars
  tasks:
    - name: Disable swap and firewall
      shell: |
        sudo swapoff -a
        sudo sed -i '/swap/ s/^/#/' /etc/fstab
        sudo ufw disable
      args:
        executable: /bin/bash
    - name: Install vim, net-tools, curl, gnupg, apt-transport-https, lsb-release, ca-certificates and dirmngr
      become: yes
      apt:
        pkg:
          - vim
          - net-tools
          - curl
          - gnupg
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - dirmngr
        update-cache: yes
    - name: Create nginx directory (for nginx.repo cert)
      command: sudo mkdir -p /etc/ssl/nginx
    - name: Copy nginx.repo.crt to /etc/ssl/nginx/
      become: yes
      copy:
        src: ~/Documents/NGINX/licenses/nginx/nginx-repo.crt
        dest: /etc/ssl/nginx/nginx-repo.crt
    - name: Copy nginx.repo.key to /etc/ssl/nginx/
      become: yes
      copy:
        src: ~/Documents/NGINX/licenses/nginx/nginx-repo.key
        dest: /etc/ssl/nginx/nginx-repo.key
    - name: Download nginx and app protect keys
      shell: | 
        sudo wget https://cs.nginx.com/static/keys/nginx_signing.key && sudo apt-key add nginx_signing.key
        sudo wget https://cs.nginx.com/static/keys/app-protect-security-updates.key && sudo apt-key add app-protect-security-updates.key
    - name: Update sources lists for nginx-plus, app-protect and modsecurity
      shell: |
        printf "deb https://pkgs.nginx.com/plus/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-plus.list
        printf "deb https://pkgs.nginx.com/app-protect/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-app-protect.list
        printf "deb https://pkgs.nginx.com/app-protect-security-updates/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee -a /etc/apt/sources.list.d/nginx-app-protect.list
        printf "deb https://pkgs.nginx.com/modsecurity/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-modsecurity.list
        sudo wget -P /etc/apt/apt.conf.d https://cs.nginx.com/static/files/90pkgs-nginx
    - name: Install nginx-plus, app-protect and modsecurity module
      become: yes
      apt: 
        pkg:
          - nginx-plus=25-2~focal
          - app-protect-plugin=3.760.0-1~focal
          - nginx-plus-module-appprotect=25+3.760.0-1~focal
          - app-protect-common=10.8.2-1~focal
          - app-protect-engine=10.8.2-1~focal
          - app-protect-compiler=10.8.2-1~focal
          - app-protect=25+3.760.0-1~focal
          - app-protect-attack-signatures
          - nginx-plus-module-modsecurity=25+1.0.2-3~focal
        update-cache: yes
    - name: Enable nginx
      command: sudo systemctl enable nginx
    - name: start nginx
      command: sudo nginx
